### ISSUE TITLE
error ListBuckets

### ISSUE THREAD

**Issue by FirstSuns** [IsmaelNascimento/aws-sdk-s3-for-unity#1]
Hello
Thanks for your git
but your project has an error
please check to attach a screenshot.
please reply
![2019-05-26_17-40-00](https://user-images.githubusercontent.com/31187166/58379950-ffa44880-7fdc-11e9-965c-c7b4583dc32d.jpg)

**Comment by oismaelash** [comment]
Hello, 

I tested the last release in Unity 2019.1.6f1 and works !

Regards,
